create_and_execute_cypher_query:
  description: >
    1. Analyze user query: {question}
    2. Consult the graph schema (provided in your goal or use the schema tool if needed).
    3. Formulate the optimal Cypher query to answer the query and prepare the input 'query' and 'parameters' arguments for the 'Neo4j Execute Cypher Query Tool'.
    4. Execute the query using the 'Neo4j Execute Cypher Query Tool' and return the raw results or error message.
  expected_output: >
    A dictionary containing the following keys:
    - 'query': A string representing the Cypher query.
    - 'query_results': A list of dictionaries representing the query results or a dictionary containing an 'error' key.

    In case of an error, just return the dictionary containing the 'error' key with the error message as the value.


# execute_query_task:
#   description: >
#     Use 'Neo4j Tool' to execute the query against the knowledge graph and 
#     output the results (list of dictionaries) or the error dictionary is returned by the tool.
  
#   expected_output: >
#     A list of dictionaries representing the query results or a dictionary containing an 'error' key.
  
#   agent: data_engineer


analyze_retrieved_data:
  description: >
    1. Review the original user query: '{question}'
    2. Examine the data retrieved (or error message) from the 'create_and_execute_cypher_query' task.
    3. If data exists, analyze it according to your specialized role (Microbial Genomics and Drug Target Analyst):
        - If KOs are present, list them, explain their functions, and explicitly discuss their essentiality and potential as drug targets for the specified microbe.
        - For other data types, provide relevant biological context.
            - Identify key microbes, metabolites, pathways, KOs mentioned or relevant.
            - Describe the relationships found.
            - Quantify findings where available.
            - Discuss potential biological implications or answer the specific question asked.
    4. If an error occurred or no data was found, clearly state this.
    5. Provide a detailed textual analysis.
  expected_output: >
    A comprehensive textual analysis of the query results in the context of the user query, 
    or a statement indicating missing data or errors.

write_report:
  description: >
    1. Take the textual analysis from the 'analyze_retrieved_data' task.
    2. Synthesize the key findings into a concise and well-structured final report.
    3. Ensure the report directly addresses the original user query and highlights any drug target implications if identified.
    4. Format the report clearly (e.g., using markdown).
  expected_output: >
    A final, formatted report summarizing the analysis and answering the user query, 
    with emphasis on drug target potential where relevant.
